In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [3]:
a.shape
(2, 3)

(2, 3)

In [4]:
libri = np.array([2,4,6])
print(libri)
figurine = np.array([1,3,5])
print(figurine)
patrimonio = libri + figurine
print(patrimonio)

[2 4 6]
[1 3 5]
[ 3  7 11]


In [5]:
librivecchi = [2,4,6]
print(librivecchi)
figurinevecchie = [1,3,5]
print(figurinevecchie)
patrimoniovecchio = librivecchi + figurinevecchie
print(patrimoniovecchio)

[2, 4, 6]
[1, 3, 5]
[2, 4, 6, 1, 3, 5]


In [6]:
# Lista numpy di un'immagine bidimensionale
pic = np.random.randn(3,4,)
print(pic)

[[-1.34955282 -0.01743846  1.18222969 -0.21861599]
 [ 0.57161529  0.22606998 -0.50009676 -0.69167195]
 [-0.31030433  0.13003543  0.94982555 -0.40675601]]


In [7]:
# Lista numpy di un'immagine tridimensionale
pic = np.random.randn(3,4,2)
print(pic)

[[[ 0.01315553  1.25279989]
  [ 2.18602894 -0.5124701 ]
  [-0.90425077  0.13091484]
  [ 0.12147522  1.30238526]]

 [[ 0.7414722  -0.05124904]
  [-0.32330655  0.92160612]
  [-0.60569665 -0.92986249]
  [-0.80979533  0.58200888]]

 [[ 1.15207595  1.00856163]
  [-0.74292386  0.32742227]
  [-1.10540066 -0.67313093]
  [-0.58202439  0.82068123]]]


In [8]:
import pandas as pd

In [9]:
diagnosis = pd.read_csv('data.csv')

In [10]:
diagnosis.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [12]:
diagnosis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5